(() => {
  const {points:P,longPath}=window.ROUTE_DATA;
  const colors={A:'#1763d4',B:'#c55514',S:'#18825e',C:'#8d429c'};
  const branches={A:['a1','moon','a2','f'],B:['b2','b3','f'],S:['s1','s2','s3','s4','s5','s6','s7','f']};
  const common=['f','c1','c2','end'];
  const titles={all:'全部进场路线',A:'A 线 · 前海出发',B:'B 线 · 世纪村出发',S:'蛇口摆渡 · 接驳飞行员公寓'};
  const $=id=>document.getElementById(id);
  let map, route='all',whole=false,selected=null,markers={},lines=[];
  function ids(){return [...new Set(route==='all'?[...branches.A,...branches.B,...branches.S,...common]:route==='S'?branches.S:[...branches[route],...common])];}
  function pick(id){selected=id;const p=P[id];const box=$('station-detail');box.hidden=false;box.replaceChildren();const strong=document.createElement('strong');strong.textContent=p.name+(p.approx?' *':'');const note=document.createElement('p');note.textContent=p.note;box.append(strong,note);if(p.source){const meta=document.createElement('p');meta.textContent='高德核对：'+p.source.checkedAt+' · '+p.status;box.append(meta);if(p.source.poiId){const link=document.createElement('a');link.href='https://www.amap.com/place/'+encodeURIComponent(p.source.poiId);link.target='_blank';link.rel='noreferrer';link.textContent='查看高德地点：'+p.source.name;box.append(link);}}document.querySelector('aside').scrollTop=0;document.querySelectorAll('.station').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.id===id)));Object.entries(markers).forEach(([key,m])=>{m.setLabel(key===id?{content:P[key].short,direction:'top',offset:new AMap.Pixel(0,-5)}:{content:''});m.setzIndex(key===id?200:100);});if(map)map.setZoomAndCenter(15,p.xy);}
  function list(){const el=$('station-list');el.replaceChildren();for(const id of ids()){const p=P[id],b=document.createElement('button');b.className='station';b.dataset.id=id;b.setAttribute('aria-pressed',String(selected===id));const code=document.createElement('span');code.className='code';code.style.background=colors[p.route];code.textContent=p.code;const name=document.createElement('span');name.textContent=p.name+(p.approx?' *':'');b.append(code,name);b.addEventListener('click',()=>pick(id));el.append(b);}$('route-title').textContent=titles[route];$('route-summary').textContent=route==='S'?'7 个接驳点 → 飞行员公寓':route==='all'?'A/B 线汇合后经广深高速进场；绿色为蛇口接驳':'飞行员公寓 → 南山区委 → 名家富居 → 广深高速 → 公司东区';}
  function fit(){if(!map)return;const visible=ids().filter(id=>whole||id!=='end').map(id=>markers[id]);map.setFitView(visible,true,[65,65,55,55],whole?13:14);}
  function draw(){list();if(!map)return;map.remove([...Object.values(markers),...lines]);markers={};lines=[];const addLine=(path,color)=>{const line=new AMap.Polyline({path,strokeColor:color,strokeWeight:5,strokeOpacity:.86,strokeStyle:'dashed',showDir:true,zIndex:40});lines.push(line);};for(const r of ['A','B','S'])if(route==='all'||route===r)addLine(branches[r].map(id=>P[id].xy),colors[r]);if(route!=='S')addLine([P.f.xy,P.c1.xy,...longPath],colors.C);map.add(lines);for(const id of ids()){const p=P[id],content=document.createElement('button');content.className='pin-hit';content.style.setProperty('--line',colors[p.route]);content.setAttribute('aria-label',p.name+(p.approx?'，大致点位':''));const pin=document.createElement('span');pin.className='pin';pin.textContent=p.code;content.append(pin);const m=new AMap.Marker({position:p.xy,content,offset:new AMap.Pixel(-22,-22),zIndex:100});m.on('click',()=>pick(id));markers[id]=m;}map.add(Object.values(markers));fit();}
  document.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',()=>{route=b.dataset.route;selected=null;$('station-detail').hidden=true;document.querySelectorAll('[data-route]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));draw();}));
  for(const [id,value] of [['south',false],['whole',true]])$(id).addEventListener('click',()=>{whole=value;$('south').setAttribute('aria-pressed',String(!whole));$('whole').setAttribute('aria-pressed',String(whole));fit();});
  $('fit').addEventListener('click',fit);$('zoom-in').addEventListener('click',()=>map?.zoomIn());$('zoom-out').addEventListener('click',()=>map?.zoomOut());$('retry').addEventListener('click',()=>location.reload());
  function fail(message){$('map-state').textContent='站点列表可用';$('error').hidden=false;$('error-message').textContent=message;}
  list();
  if(!window.AMAP_KEY){fail('尚未配置地图服务。');return;}
  const timeout=setTimeout(()=>{if(!map)fail('请检查网络连接，或稍后重试。');},20000);
  window.onAMapReady=()=>{clearTimeout(timeout);try{map=new AMap.Map('map',{viewMode:'2D',center:[113.94,22.525],zoom:12,dragEnable:true,zoomEnable:true,touchZoom:true,rotateEnable:false,resizeEnable:true});map.on('complete',()=>{$('map-state').textContent='高德地图 · 可交互';$('error').hidden=true;});draw();new ResizeObserver(()=>{map.resize();fit();}).observe($('map'));}catch(e){fail('地图初始化失败，请检查高德应用配置。');}};
  const sdk=document.createElement('script');sdk.src='https://webapi.amap.com/maps?v=2.0&key='+encodeURIComponent(window.AMAP_KEY)+'&callback=onAMapReady';sdk.onerror=()=>{clearTimeout(timeout);fail('高德地图服务暂时无法连接，请检查网络后重试。');};document.head.append(sdk);
})();
